# encoding: UTF-8
require 'rubygems'
require 'correios/sro'
require 'correios/sro/destino'
require 'correios/sro/evento'
require 'correios/sro/objeto'
require 'correios/sro/parser'
require 'correios/sro/rastreador'
require 'correios/sro/string'
require 'correios/sro/web_service'
